// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type Apartament struct {
	ID             int64
	Name           string
	Street         string
	BuildingNumber string
	BuildingName   string
	FlatNumber     string
	OwnerID        int64
}

type Expense struct {
	ID          int64
	Amount      float64
	ExpenseDate time.Time
	Description string
	CategoryID  int64
	RepairID    interface{}
}

type Expensecategory struct {
	ID   int64
	Name string
}

type Faultreport struct {
	ID           int64
	Title        string
	Description  string
	DateReported time.Time
	StatusID     int64
	ApartmentID  int64
}

type Faultstatus struct {
	ID   int64
	Name string
}

type FinancialRecord struct {
	Type             string
	SourceID         int64
	Amount           float64
	RecordDate       time.Time
	Description      string
	RelatedPaymentID int64
	RelatedExpenseID interface{}
	UserName         string
	ApartmentName    string
}

type Owner struct {
	ID    int64
	Name  string
	Email string
	Phone string
}

type Payment struct {
	ID                   int64
	UserID               int64
	ApartamentID         int64
	Amount               float64
	PaymentDate          time.Time
	StatusID             int64
	PaymentMethodID      int64
	TransactionReference sql.NullString
}

type Paymentmethod struct {
	ID   int64
	Name string
}

type Paymentstatus struct {
	ID   int64
	Name string
}

type Pricinghistory struct {
	ID          int64
	ApartmentID int64
	Date        time.Time
	Price       float64
	IsCurrent   sql.NullBool
}

type RentingHistory struct {
	ID          int64
	ApartmentID int64
	UserID      int64
	StartDate   time.Time
	EndDate     sql.NullTime
}

type Repair struct {
	ID              int64
	Title           string
	FaultReportID   sql.NullInt64
	DateAssigned    time.Time
	DateCompleted   sql.NullTime
	StatusID        int64
	SubcontractorID sql.NullInt64
}

type RepairHistory struct {
	ID               int64
	RentingHistoryID sql.NullInt64
	FaultReportID    sql.NullInt64
}

type Repairstatus struct {
	ID   int64
	Name string
}

type Role struct {
	ID   int64
	Name string
}

type Speciality struct {
	ID   int64
	Name string
}

type Subcontractor struct {
	ID           int64
	UserID       int64
	Address      string
	Nip          string
	SpecialityID int64
}

type User struct {
	ID       int64
	Name     string
	Email    string
	Phone    string
	RoleID   int64
	Password string
}
